name: CI

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install composer dependencies
      uses: php-actions/composer@v1
    - name: Run PHPUnit tests
      run: composer run-script test
